# permissions for end users to view opensearches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opensearch-viewer-role
rules:
- apiGroups:
  - opensearch.k8s.webcenter.fr
  resources:
  - opensearches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - opensearch.k8s.webcenter.fr
  resources:
  - opensearches/status
  verbs:
  - get
