# permissions for end users to edit opensearches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opensearch-editor-role
rules:
- apiGroups:
  - opensearch.k8s.webcenter.fr
  resources:
  - opensearches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opensearch.k8s.webcenter.fr
  resources:
  - opensearches/status
  verbs:
  - get
